package uk.selflearning.apache.camel.runner;

import com.azure.messaging.servicebus.ServiceBusClientBuilder;
import com.azure.messaging.servicebus.ServiceBusMessage;
import com.azure.messaging.servicebus.ServiceBusSenderClient;
import org.junit.jupiter.api.Test;

import java.util.Map;

/**
 * One-shot runner: sends an Azure Function-style message to the input queue so the
 * running main app processes it and deposits the result in the output queue, where the
 * inspection endpoint (localhost:8081) can peek at it.
 *
 * Prerequisites: docker compose up -d && ./mvnw spring-boot:run (main app running)
 *
 * Simulates a message produced by an Azure Function. Unlike Event Grid, a function
 * owns the business context and explicitly sets:
 *
 *   body                  — the business payload (e.g. serialised order JSON)
 *   subject               — a message-type label the consumer uses to identify the event
 *   contentType           — "application/json"
 *   correlationId         — a trace/request ID set by the function for end-to-end tracking
 *   applicationProperties — domain metadata the function attaches (e.g. source system, priority)
 *   messageId             — UUID auto-generated by the SDK before hitting the broker
 *
 * No exception-triggering flags are set — this message completes the full pipeline
 * (Steps 1–7) and is forwarded to the output queue.
 *
 * Run with: ./mvnw test -Dtest=AzureFunctionMessageRunner -DfailIfNoTests=false
 */
class AzureFunctionMessageRunner {

    private static final String CONNECTION_STRING =
            "Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;" +
            "SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;";

    @Test
    void run() {
        try (ServiceBusSenderClient sender = new ServiceBusClientBuilder()
                .connectionString(CONNECTION_STRING)
                .sender()
                .queueName("input")
                .buildClient()) {

            ServiceBusMessage msg = new ServiceBusMessage("Hello from AzureFunctionMessageRunner");
            msg.setSubject("OrderReceived");
            msg.setContentType("application/json");
            msg.setCorrelationId("corr-123");
            msg.getApplicationProperties().putAll(Map.of(
                    "source", "order-service",
                    "priority", "high"
            ));
            sender.sendMessage(msg);
            System.out.println("Message sent to input queue.");
        }
    }
}
