package uk.selflearning.apache.camel.runner;

import com.azure.messaging.servicebus.ServiceBusClientBuilder;
import com.azure.messaging.servicebus.ServiceBusMessage;
import com.azure.messaging.servicebus.ServiceBusSenderClient;
import org.junit.jupiter.api.Test;

/**
 * One-shot runner: sends a blob-created event to the input queue so the running
 * main app processes it and deposits the result in the output queue, where the
 * inspection endpoint (localhost:8081) can peek at it.
 *
 * Prerequisites: docker compose up -d && ./mvnw spring-boot:run (main app running)
 *
 * Simulates a message produced by Azure Event Grid when a file is dropped into
 * Azure Blob Storage. Event Grid delivers blob-created events directly to a
 * Service Bus queue. It populates:
 *
 *   body          — the Event Grid event JSON (blob name, container, size, etc.)
 *   subject       — the blob path, e.g. /blobServices/default/containers/uploads/blobs/order.json
 *   contentType   — "application/json" (Event Grid always sets this)
 *   messageId     — UUID auto-generated by the SDK before hitting the broker
 *
 * Everything else is null: correlationId, replyTo, sessionId, partitionKey,
 * applicationProperties. Event Grid has no knowledge of application-level metadata.
 *
 * No exception-triggering flags are set — this message completes the full pipeline
 * (Steps 1–7) and is forwarded to the output queue.
 *
 * Run with: ./mvnw test -Dtest=EventGridBlobEventRunner -DfailIfNoTests=false
 */
class EventGridBlobEventRunner {

    private static final String CONNECTION_STRING =
            "Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;" +
            "SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;";

    @Test
    void run() {
        try (ServiceBusSenderClient sender = new ServiceBusClientBuilder()
                .connectionString(CONNECTION_STRING)
                .sender()
                .queueName("input")
                .buildClient()) {

            ServiceBusMessage msg = new ServiceBusMessage("Hello from EventGridBlobEventRunner");
            msg.setSubject("/blobServices/default/containers/uploads/blobs/order.json");
            msg.setContentType("application/json");
            sender.sendMessage(msg);
            System.out.println("Message sent to input queue.");
        }
    }
}
